version: "3"
services:
  env:
    build: ./docker
    volumes:
      - ./:/code
    working_dir: /code
    tty: true
    ports:
      - 8889:8889
    command: jupyter notebook --ip=0.0.0.0 --port 8889 --allow-root --no-browser
